data:
  train_path: /home/app/datasets/test
  val_path: /home/app/datasets/test
  sr: 16000
  duration: 30
  n_mels: 128
  n_fft: 1024
  batchsize: 128

model:
  firstlevel:
    in_channels: 1
    mid_channels: [2, 4, 8, 16, 32, 64]
    out_channels: 1
  secondlevel:
    in_channels: 1
    mid_channels: [2, 4, 8]
    input_size: 464   # 1288
    lstm_hidden_size1: 256
    lstm_hidden_size2: 128
    cls_count: 10
    latent_features: 512
    droprate: 0.25

train:
  manual_seed: 12138
  lr: 0.00001

  trainer:
    devices: 1
    accelerator: 'gpu'
    strategy: 'ddp'
    max_epochs: 100

  logging:
    save_dir: "logs/"
    name: 'CantoneseClsLog'



